name: Poll Audit Log

# Run it every 30 minutes
on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Get the latest cursor file from the repo
      - run: export LAST_CURSOR=$(cat .last-cursor-update)
      # Run the script with the latest cursor if present in the repo
      - run: npm install
      - run: |
          if [ -z "$LAST_CURSOR" ]; then
            echo "FIRST TIME RUNNING AUDIT LOG POLL"
            npm start -- --pretty --token ${{secrets.AUDIT_LOG_TOKEN}} --org ${{secrets.ORG_NAME}} >> audit-log-output.json
          else
            echo "RUNNING AUDIT LOG POLL FROM $LAST_CURSOR"
            npm start -- --pretty --token ${{secrets.AUDIT_LOG_TOKEN}} --org ${{secrets.ORG_NAME}} --cursor $LAST_CURSOR >> audit-log-output.json
          fi
      # Cat the output. Optionally send it somewhere else
      - run: cat audit-log-output.json
      # Commit the .last-cursor-update so we can reuse it in the upcoming workflows
      - name: Commit cursor
        uses: EndBug/add-and-commit@v5
        with:
          author_name: Audit Log Integration
          author_email: alwell-kevin@github.com
          message: "updating cursor for audit log"
          add: ".last-cursor-update"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
